remote_theme: daviddarnes/alembic@main
plugins:
  - jekyll-remote-theme
title: Jarett Conner — CS Capstone E‑Portfolio
description: Welcome, self‑assessment, single artifact with enhancements, narratives across three categories, and a code review video.
url: "https://Jconner3.github.io"
baseurl: "/Jconner3"

